title: 《如何回到寒假第一天》官网
theme: minima
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /posts/:title/
    # 禁用默认页脚
minima:
  show_footer: false
# 在文件末尾添加以下配置
artalk:
  server: "http://110.42.45.236:23366"  # Artalk 服务地址
  site: "MyBlog"                        # 需与后台站点名一致
  placeholder: "理性发言，共建社区..."  
  pageKey: "{{ page.url }}"             # 文章唯一标识
  darkMode: false
  locale: "zh"
  nestMax: 3                            # 评论嵌套层级
  imgUpload: true                       # 开启图片上传
